
package rs.ruta.services;

import java.util.List;
import java.util.concurrent.Future;
import javax.activation.DataHandler;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;
import oasis.names.specification.ubl.schema.xsd.catalogue_21.CatalogueType;
import oasis.names.specification.ubl.schema.xsd.cataloguedeletion_21.CatalogueDeletionType;
import oasis.names.specification.ubl.schema.xsd.commonaggregatecomponents_21.PartyType;
import rs.ruta.common.BugReport;
import rs.ruta.common.ReportAttachment;
import rs.ruta.common.RutaVersion;
import rs.ruta.common.SearchCriterion;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Server", targetNamespace = "http://ruta.rs/services")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Server {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<rs.ruta.services.InsertFileResponse>
     */
    @WebMethod(operationName = "InsertFile")
    @RequestWrapper(localName = "InsertFile", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.InsertFile")
    @ResponseWrapper(localName = "InsertFileResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.InsertFileResponse")
    public Response<InsertFileResponse> insertFileAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        DataHandler arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "InsertFile")
    @RequestWrapper(localName = "InsertFile", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.InsertFile")
    @ResponseWrapper(localName = "InsertFileResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.InsertFileResponse")
    public Future<?> insertFileAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        DataHandler arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<InsertFileResponse> asyncHandler);

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws RutaException
     */
    @WebMethod(operationName = "InsertFile")
    @RequestWrapper(localName = "InsertFile", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.InsertFile")
    @ResponseWrapper(localName = "InsertFileResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.InsertFileResponse")
    public void insertFile(
        @WebParam(name = "arg0", targetNamespace = "")
        DataHandler arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws RutaException
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<rs.ruta.services.SearchPartyResponse>
     */
    @WebMethod(operationName = "SearchParty")
    @RequestWrapper(localName = "SearchParty", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.SearchParty")
    @ResponseWrapper(localName = "SearchPartyResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.SearchPartyResponse")
    public Response<SearchPartyResponse> searchPartyAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        SearchCriterion arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "SearchParty")
    @RequestWrapper(localName = "SearchParty", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.SearchParty")
    @ResponseWrapper(localName = "SearchPartyResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.SearchPartyResponse")
    public Future<?> searchPartyAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        SearchCriterion arg1,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<SearchPartyResponse> asyncHandler);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<oasis.names.specification.ubl.schema.xsd.commonaggregatecomponents_21.PartyType>
     * @throws RutaException
     */
    @WebMethod(operationName = "SearchParty")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SearchParty", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.SearchParty")
    @ResponseWrapper(localName = "SearchPartyResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.SearchPartyResponse")
    public List<PartyType> searchParty(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        SearchCriterion arg1)
        throws RutaException
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<rs.ruta.services.UpdateCatalogueResponse>
     */
    @WebMethod(operationName = "UpdateCatalogue")
    @RequestWrapper(localName = "UpdateCatalogue", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.UpdateCatalogue")
    @ResponseWrapper(localName = "UpdateCatalogueResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.UpdateCatalogueResponse")
    public Response<UpdateCatalogueResponse> updateCatalogueAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        CatalogueType arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "UpdateCatalogue")
    @RequestWrapper(localName = "UpdateCatalogue", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.UpdateCatalogue")
    @ResponseWrapper(localName = "UpdateCatalogueResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.UpdateCatalogueResponse")
    public Future<?> updateCatalogueAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        CatalogueType arg1,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<UpdateCatalogueResponse> asyncHandler);

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws RutaException
     */
    @WebMethod(operationName = "UpdateCatalogue")
    @RequestWrapper(localName = "UpdateCatalogue", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.UpdateCatalogue")
    @ResponseWrapper(localName = "UpdateCatalogueResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.UpdateCatalogueResponse")
    public void updateCatalogue(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        CatalogueType arg1)
        throws RutaException
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<rs.ruta.services.InsertBugReportResponse>
     */
    @WebMethod(operationName = "InsertBugReport")
    @RequestWrapper(localName = "InsertBugReport", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.InsertBugReport")
    @ResponseWrapper(localName = "InsertBugReportResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.InsertBugReportResponse")
    public Response<InsertBugReportResponse> insertBugReportAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        BugReport arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "InsertBugReport")
    @RequestWrapper(localName = "InsertBugReport", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.InsertBugReport")
    @ResponseWrapper(localName = "InsertBugReportResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.InsertBugReportResponse")
    public Future<?> insertBugReportAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        BugReport arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<InsertBugReportResponse> asyncHandler);

    /**
     * 
     * @param arg0
     * @throws RutaException
     */
    @WebMethod(operationName = "InsertBugReport")
    @RequestWrapper(localName = "InsertBugReport", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.InsertBugReport")
    @ResponseWrapper(localName = "InsertBugReportResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.InsertBugReportResponse")
    public void insertBugReport(
        @WebParam(name = "arg0", targetNamespace = "")
        BugReport arg0)
        throws RutaException
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<rs.ruta.services.UpdateRutaClientResponse>
     */
    @WebMethod(operationName = "UpdateRutaClient")
    @RequestWrapper(localName = "UpdateRutaClient", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.UpdateRutaClient")
    @ResponseWrapper(localName = "UpdateRutaClientResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.UpdateRutaClientResponse")
    public Response<UpdateRutaClientResponse> updateRutaClientAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "UpdateRutaClient")
    @RequestWrapper(localName = "UpdateRutaClient", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.UpdateRutaClient")
    @ResponseWrapper(localName = "UpdateRutaClientResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.UpdateRutaClientResponse")
    public Future<?> updateRutaClientAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<UpdateRutaClientResponse> asyncHandler);

    /**
     * 
     * @param arg0
     * @return
     *     returns rs.ruta.common.RutaVersion
     * @throws RutaException
     */
    @WebMethod(operationName = "UpdateRutaClient")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "UpdateRutaClient", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.UpdateRutaClient")
    @ResponseWrapper(localName = "UpdateRutaClientResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.UpdateRutaClientResponse")
    public RutaVersion updateRutaClient(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws RutaException
    ;

    /**
     * 
     * @return
     *     returns javax.xml.ws.Response<rs.ruta.services.FindAllPartiesResponse>
     */
    @WebMethod(operationName = "FindAllParties")
    @RequestWrapper(localName = "FindAllParties", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.FindAllParties")
    @ResponseWrapper(localName = "FindAllPartiesResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.FindAllPartiesResponse")
    public Response<FindAllPartiesResponse> findAllPartiesAsync();

    /**
     * 
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "FindAllParties")
    @RequestWrapper(localName = "FindAllParties", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.FindAllParties")
    @ResponseWrapper(localName = "FindAllPartiesResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.FindAllPartiesResponse")
    public Future<?> findAllPartiesAsync(
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<FindAllPartiesResponse> asyncHandler);

    /**
     * 
     * @return
     *     returns java.util.List<oasis.names.specification.ubl.schema.xsd.commonaggregatecomponents_21.PartyType>
     * @throws RutaException
     */
    @WebMethod(operationName = "FindAllParties")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FindAllParties", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.FindAllParties")
    @ResponseWrapper(localName = "FindAllPartiesResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.FindAllPartiesResponse")
    public List<PartyType> findAllParties()
        throws RutaException
    ;

    /**
     * 
     * @return
     *     returns javax.xml.ws.Response<rs.ruta.services.FindAllBugReportsResponse>
     */
    @WebMethod(operationName = "FindAllBugReports")
    @RequestWrapper(localName = "FindAllBugReports", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.FindAllBugReports")
    @ResponseWrapper(localName = "FindAllBugReportsResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.FindAllBugReportsResponse")
    public Response<FindAllBugReportsResponse> findAllBugReportsAsync();

    /**
     * 
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "FindAllBugReports")
    @RequestWrapper(localName = "FindAllBugReports", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.FindAllBugReports")
    @ResponseWrapper(localName = "FindAllBugReportsResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.FindAllBugReportsResponse")
    public Future<?> findAllBugReportsAsync(
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<FindAllBugReportsResponse> asyncHandler);

    /**
     * 
     * @return
     *     returns java.util.List<rs.ruta.common.BugReport>
     * @throws RutaException
     */
    @WebMethod(operationName = "FindAllBugReports")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FindAllBugReports", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.FindAllBugReports")
    @ResponseWrapper(localName = "FindAllBugReportsResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.FindAllBugReportsResponse")
    public List<BugReport> findAllBugReports()
        throws RutaException
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<rs.ruta.services.InsertCatalogueResponse>
     */
    @WebMethod(operationName = "InsertCatalogue")
    @RequestWrapper(localName = "InsertCatalogue", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.InsertCatalogue")
    @ResponseWrapper(localName = "InsertCatalogueResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.InsertCatalogueResponse")
    public Response<InsertCatalogueResponse> insertCatalogueAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        CatalogueType arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "InsertCatalogue")
    @RequestWrapper(localName = "InsertCatalogue", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.InsertCatalogue")
    @ResponseWrapper(localName = "InsertCatalogueResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.InsertCatalogueResponse")
    public Future<?> insertCatalogueAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        CatalogueType arg1,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<InsertCatalogueResponse> asyncHandler);

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws RutaException
     */
    @WebMethod(operationName = "InsertCatalogue")
    @RequestWrapper(localName = "InsertCatalogue", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.InsertCatalogue")
    @ResponseWrapper(localName = "InsertCatalogueResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.InsertCatalogueResponse")
    public void insertCatalogue(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        CatalogueType arg1)
        throws RutaException
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<rs.ruta.services.SearchCatalogueResponse>
     */
    @WebMethod(operationName = "SearchCatalogue")
    @RequestWrapper(localName = "SearchCatalogue", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.SearchCatalogue")
    @ResponseWrapper(localName = "SearchCatalogueResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.SearchCatalogueResponse")
    public Response<SearchCatalogueResponse> searchCatalogueAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        SearchCriterion arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "SearchCatalogue")
    @RequestWrapper(localName = "SearchCatalogue", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.SearchCatalogue")
    @ResponseWrapper(localName = "SearchCatalogueResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.SearchCatalogueResponse")
    public Future<?> searchCatalogueAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        SearchCriterion arg1,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<SearchCatalogueResponse> asyncHandler);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<oasis.names.specification.ubl.schema.xsd.catalogue_21.CatalogueType>
     * @throws RutaException
     */
    @WebMethod(operationName = "SearchCatalogue")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SearchCatalogue", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.SearchCatalogue")
    @ResponseWrapper(localName = "SearchCatalogueResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.SearchCatalogueResponse")
    public List<CatalogueType> searchCatalogue(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        SearchCriterion arg1)
        throws RutaException
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<rs.ruta.services.DeleteCatalogueResponse>
     */
    @WebMethod(operationName = "DeleteCatalogue")
    @RequestWrapper(localName = "DeleteCatalogue", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.DeleteCatalogue")
    @ResponseWrapper(localName = "DeleteCatalogueResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.DeleteCatalogueResponse")
    public Response<DeleteCatalogueResponse> deleteCatalogueAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        CatalogueDeletionType arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "DeleteCatalogue")
    @RequestWrapper(localName = "DeleteCatalogue", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.DeleteCatalogue")
    @ResponseWrapper(localName = "DeleteCatalogueResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.DeleteCatalogueResponse")
    public Future<?> deleteCatalogueAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        CatalogueDeletionType arg1,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<DeleteCatalogueResponse> asyncHandler);

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws RutaException
     */
    @WebMethod(operationName = "DeleteCatalogue")
    @RequestWrapper(localName = "DeleteCatalogue", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.DeleteCatalogue")
    @ResponseWrapper(localName = "DeleteCatalogueResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.DeleteCatalogueResponse")
    public void deleteCatalogue(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        CatalogueDeletionType arg1)
        throws RutaException
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<rs.ruta.services.InsertAttachmentResponse>
     */
    @WebMethod(operationName = "InsertAttachment")
    @RequestWrapper(localName = "InsertAttachment", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.InsertAttachment")
    @ResponseWrapper(localName = "InsertAttachmentResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.InsertAttachmentResponse")
    public Response<InsertAttachmentResponse> insertAttachmentAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        ReportAttachment arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "InsertAttachment")
    @RequestWrapper(localName = "InsertAttachment", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.InsertAttachment")
    @ResponseWrapper(localName = "InsertAttachmentResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.InsertAttachmentResponse")
    public Future<?> insertAttachmentAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        ReportAttachment arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<InsertAttachmentResponse> asyncHandler);

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws RutaException
     */
    @WebMethod(operationName = "InsertAttachment")
    @RequestWrapper(localName = "InsertAttachment", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.InsertAttachment")
    @ResponseWrapper(localName = "InsertAttachmentResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.InsertAttachmentResponse")
    public void insertAttachment(
        @WebParam(name = "arg0", targetNamespace = "")
        ReportAttachment arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws RutaException
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<rs.ruta.services.UpdatePartyResponse>
     */
    @WebMethod(operationName = "UpdateParty")
    @RequestWrapper(localName = "UpdateParty", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.UpdateParty")
    @ResponseWrapper(localName = "UpdatePartyResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.UpdatePartyResponse")
    public Response<UpdatePartyResponse> updatePartyAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        PartyType arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "UpdateParty")
    @RequestWrapper(localName = "UpdateParty", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.UpdateParty")
    @ResponseWrapper(localName = "UpdatePartyResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.UpdatePartyResponse")
    public Future<?> updatePartyAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        PartyType arg1,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<UpdatePartyResponse> asyncHandler);

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws RutaException
     */
    @WebMethod(operationName = "UpdateParty")
    @RequestWrapper(localName = "UpdateParty", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.UpdateParty")
    @ResponseWrapper(localName = "UpdatePartyResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.UpdatePartyResponse")
    public void updateParty(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        PartyType arg1)
        throws RutaException
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<rs.ruta.services.NotifyUpdateResponse>
     */
    @WebMethod(operationName = "NotifyUpdate")
    @RequestWrapper(localName = "NotifyUpdate", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.NotifyUpdate")
    @ResponseWrapper(localName = "NotifyUpdateResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.NotifyUpdateResponse")
    public Response<NotifyUpdateResponse> notifyUpdateAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        RutaVersion arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "NotifyUpdate")
    @RequestWrapper(localName = "NotifyUpdate", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.NotifyUpdate")
    @ResponseWrapper(localName = "NotifyUpdateResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.NotifyUpdateResponse")
    public Future<?> notifyUpdateAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        RutaVersion arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<NotifyUpdateResponse> asyncHandler);

    /**
     * 
     * @param arg0
     * @throws RutaException
     */
    @WebMethod(operationName = "NotifyUpdate")
    @RequestWrapper(localName = "NotifyUpdate", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.NotifyUpdate")
    @ResponseWrapper(localName = "NotifyUpdateResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.NotifyUpdateResponse")
    public void notifyUpdate(
        @WebParam(name = "arg0", targetNamespace = "")
        RutaVersion arg0)
        throws RutaException
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<rs.ruta.services.FindCatalogueResponse>
     */
    @WebMethod(operationName = "FindCatalogue")
    @RequestWrapper(localName = "FindCatalogue", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.FindCatalogue")
    @ResponseWrapper(localName = "FindCatalogueResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.FindCatalogueResponse")
    public Response<FindCatalogueResponse> findCatalogueAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "FindCatalogue")
    @RequestWrapper(localName = "FindCatalogue", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.FindCatalogue")
    @ResponseWrapper(localName = "FindCatalogueResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.FindCatalogueResponse")
    public Future<?> findCatalogueAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<FindCatalogueResponse> asyncHandler);

    /**
     * 
     * @param arg0
     * @return
     *     returns oasis.names.specification.ubl.schema.xsd.catalogue_21.CatalogueType
     * @throws RutaException
     */
    @WebMethod(operationName = "FindCatalogue")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FindCatalogue", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.FindCatalogue")
    @ResponseWrapper(localName = "FindCatalogueResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.FindCatalogueResponse")
    public CatalogueType findCatalogue(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws RutaException
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<rs.ruta.services.RegisterUserResponse>
     */
    @WebMethod(operationName = "RegisterUser")
    @RequestWrapper(localName = "RegisterUser", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.RegisterUser")
    @ResponseWrapper(localName = "RegisterUserResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.RegisterUserResponse")
    public Response<RegisterUserResponse> registerUserAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "RegisterUser")
    @RequestWrapper(localName = "RegisterUser", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.RegisterUser")
    @ResponseWrapper(localName = "RegisterUserResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.RegisterUserResponse")
    public Future<?> registerUserAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<RegisterUserResponse> asyncHandler);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws RutaException
     */
    @WebMethod(operationName = "RegisterUser")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "RegisterUser", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.RegisterUser")
    @ResponseWrapper(localName = "RegisterUserResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.RegisterUserResponse")
    public String registerUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws RutaException
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<rs.ruta.services.InsertPartyResponse>
     */
    @WebMethod(operationName = "InsertParty")
    @RequestWrapper(localName = "InsertParty", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.InsertParty")
    @ResponseWrapper(localName = "InsertPartyResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.InsertPartyResponse")
    public Response<InsertPartyResponse> insertPartyAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        PartyType arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "InsertParty")
    @RequestWrapper(localName = "InsertParty", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.InsertParty")
    @ResponseWrapper(localName = "InsertPartyResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.InsertPartyResponse")
    public Future<?> insertPartyAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        PartyType arg1,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<InsertPartyResponse> asyncHandler);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws RutaException
     */
    @WebMethod(operationName = "InsertParty")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "InsertParty", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.InsertParty")
    @ResponseWrapper(localName = "InsertPartyResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.InsertPartyResponse")
    public String insertParty(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        PartyType arg1)
        throws RutaException
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<rs.ruta.services.InsertImageResponse>
     */
    @WebMethod(operationName = "InsertImage")
    @RequestWrapper(localName = "InsertImage", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.InsertImage")
    @ResponseWrapper(localName = "InsertImageResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.InsertImageResponse")
    public Response<InsertImageResponse> insertImageAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        DataHandler arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "InsertImage")
    @RequestWrapper(localName = "InsertImage", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.InsertImage")
    @ResponseWrapper(localName = "InsertImageResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.InsertImageResponse")
    public Future<?> insertImageAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        DataHandler arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<InsertImageResponse> asyncHandler);

    /**
     * 
     * @param arg0
     * @throws RutaException
     */
    @WebMethod(operationName = "InsertImage")
    @RequestWrapper(localName = "InsertImage", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.InsertImage")
    @ResponseWrapper(localName = "InsertImageResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.InsertImageResponse")
    public void insertImage(
        @WebParam(name = "arg0", targetNamespace = "")
        DataHandler arg0)
        throws RutaException
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<rs.ruta.services.DeleteUserResponse>
     */
    @WebMethod(operationName = "DeleteUser")
    @RequestWrapper(localName = "DeleteUser", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.DeleteUser")
    @ResponseWrapper(localName = "DeleteUserResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.DeleteUserResponse")
    public Response<DeleteUserResponse> deleteUserAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "DeleteUser")
    @RequestWrapper(localName = "DeleteUser", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.DeleteUser")
    @ResponseWrapper(localName = "DeleteUserResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.DeleteUserResponse")
    public Future<?> deleteUserAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<DeleteUserResponse> asyncHandler);

    /**
     * 
     * @param arg0
     * @throws RutaException
     */
    @WebMethod(operationName = "DeleteUser")
    @RequestWrapper(localName = "DeleteUser", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.DeleteUser")
    @ResponseWrapper(localName = "DeleteUserResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.DeleteUserResponse")
    public void deleteUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws RutaException
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<rs.ruta.services.FindBugReportResponse>
     */
    @WebMethod(operationName = "FindBugReport")
    @RequestWrapper(localName = "FindBugReport", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.FindBugReport")
    @ResponseWrapper(localName = "FindBugReportResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.FindBugReportResponse")
    public Response<FindBugReportResponse> findBugReportAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "FindBugReport")
    @RequestWrapper(localName = "FindBugReport", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.FindBugReport")
    @ResponseWrapper(localName = "FindBugReportResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.FindBugReportResponse")
    public Future<?> findBugReportAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<FindBugReportResponse> asyncHandler);

    /**
     * 
     * @param arg0
     * @return
     *     returns rs.ruta.common.BugReport
     * @throws RutaException
     */
    @WebMethod(operationName = "FindBugReport")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FindBugReport", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.FindBugReport")
    @ResponseWrapper(localName = "FindBugReportResponse", targetNamespace = "http://ruta.rs/services", className = "rs.ruta.services.FindBugReportResponse")
    public BugReport findBugReport(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws RutaException
    ;

}
