
package rs.ruta.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import oasis.names.specification.ubl.schema.xsd.catalogue_2.CatalogueType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Server", targetNamespace = "http://server.ruta.rs/")
@XmlSeeAlso({
    oasis.names.specification.ubl.schema.xsd.catalogue_2.ObjectFactory.class,
    oasis.names.specification.ubl.schema.xsd.commonaggregatecomponents_2.ObjectFactory.class,
    oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.ObjectFactory.class,
    oasis.names.specification.ubl.schema.xsd.commonextensioncomponents_2.ObjectFactory.class,
    oasis.names.specification.ubl.schema.xsd.signaturebasiccomponents_2.ObjectFactory.class,
    oasis.names.specification.ubl.schema.xsd.unqualifieddatatypes_2.ObjectFactory.class,
    rs.ruta.services.ObjectFactory.class,
    un.unece.uncefact.data.specification.corecomponenttypeschemamodule._2.ObjectFactory.class
})
public interface Server {


    /**
     * 
     * @return
     *     returns oasis.names.specification.ubl.schema.xsd.catalogue_2.CatalogueType
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDocument", targetNamespace = "http://server.ruta.rs/", className = "rs.ruta.server.GetDocument")
    @ResponseWrapper(localName = "getDocumentResponse", targetNamespace = "http://server.ruta.rs/", className = "rs.ruta.server.GetDocumentResponse")
    public CatalogueType getDocument();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "putDocument", targetNamespace = "http://server.ruta.rs/", className = "rs.ruta.server.PutDocument")
    @ResponseWrapper(localName = "putDocumentResponse", targetNamespace = "http://server.ruta.rs/", className = "rs.ruta.server.PutDocumentResponse")
    public void putDocument(
        @WebParam(name = "arg0", targetNamespace = "")
        CatalogueType arg0);

}
