
package rs.ruta.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CDRService", targetNamespace = "http://server.ruta.rs/", wsdlLocation = "http://localhost:8080/Ruta-0.0.1/CDR?wsdl")
public class CDRService
    extends Service
{

    private final static URL CDRSERVICE_WSDL_LOCATION;
    private final static WebServiceException CDRSERVICE_EXCEPTION;
    private final static QName CDRSERVICE_QNAME = new QName("http://server.ruta.rs/", "CDRService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Ruta-0.0.1/CDR?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CDRSERVICE_WSDL_LOCATION = url;
        CDRSERVICE_EXCEPTION = e;
    }

    public CDRService() {
        super(__getWsdlLocation(), CDRSERVICE_QNAME);
    }

    public CDRService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CDRSERVICE_QNAME, features);
    }

    public CDRService(URL wsdlLocation) {
        super(wsdlLocation, CDRSERVICE_QNAME);
    }

    public CDRService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CDRSERVICE_QNAME, features);
    }

    public CDRService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CDRService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Server
     */
    @WebEndpoint(name = "CDRPort")
    public Server getCDRPort() {
        return super.getPort(new QName("http://server.ruta.rs/", "CDRPort"), Server.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Server
     */
    @WebEndpoint(name = "CDRPort")
    public Server getCDRPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.ruta.rs/", "CDRPort"), Server.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CDRSERVICE_EXCEPTION!= null) {
            throw CDRSERVICE_EXCEPTION;
        }
        return CDRSERVICE_WSDL_LOCATION;
    }

}
