
package rs.ruta.server.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.6
 * Wed Jun 14 12:13:37 CEST 2017
 * Generated source version: 3.1.6
 */

@XmlRootElement(name = "getDocument", namespace = "http://server.ruta.rs/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getDocument", namespace = "http://server.ruta.rs/")

public class GetDocument {


}

