
package rs.ruta.server.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.6
 * Wed Jun 14 12:13:38 CEST 2017
 * Generated source version: 3.1.6
 */

@XmlRootElement(name = "getDocumentResponse", namespace = "http://server.ruta.rs/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getDocumentResponse", namespace = "http://server.ruta.rs/")

public class GetDocumentResponse {

    @XmlElement(name = "return")
    private oasis.names.specification.ubl.schema.xsd.catalogue_2.CatalogueType _return;

    public oasis.names.specification.ubl.schema.xsd.catalogue_2.CatalogueType getReturn() {
        return this._return;
    }

    public void setReturn(oasis.names.specification.ubl.schema.xsd.catalogue_2.CatalogueType new_return)  {
        this._return = new_return;
    }

}

